### ISSUE TITLE
NewConnectionError: Max retries exceeded

### ISSUE THREAD

**Issue by YutoUchimi** [YutoUchimi/sesame_ros#3]
When I call `~get_status` service, the following error message appears.
```
$ rosservice call /sesame_server/get_status 
ERROR: service [/sesame_server/get_status] responded with an error: error processing request: HTTPSConnectionPool(host='api.candyhouse.co', port=443): Max retries exceeded with url: /public/sesames (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1aa9636a10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

Also, in the terminal in which sesame_server launched, the following message appears.
```
[ERROR] [WallTime: 1538466054.298965] Error processing request: HTTPSConnectionPool(host='api.candyhouse.co', port=443): Max retries exceeded with url: /public/sesames (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1aa9636a10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/yuto/Projects/catkin_ws/src/sesame_ros/node_scripts/sesame_server.py", line 72, in get_sesame_status\n    return StatusResponse(*self._get_sesame_status())\n', '  File "/home/yuto/Projects/catkin_ws/src/sesame_ros/node_scripts/sesame_server.py", line 56, in _get_sesame_status\n    self._get_sesame()\n', '  File "/home/yuto/Projects/catkin_ws/src/sesame_ros/node_scripts/sesame_server.py", line 35, in _get_sesame\n    headers={\'Authorization\': self.auth_token})\n', '  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 72, in get\n    return request(\'get\', url, params=params, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request\n    return session.request(method=method, url=url, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 512, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 513, in send\n    raise ConnectionError(e, request=request)\n', "ConnectionError: HTTPSConnectionPool(host='api.candyhouse.co', port=443): Max retries exceeded with url: /public/sesames (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1aa9636a10>: Failed to establish a new connection: [Errno -2] Name or service not known',))\n"]
```

How can I solve this?

**Comment by YutoUchimi** [comment]
Can you check your PC's Internet status?

**Comment by YutoUchimi** [comment]
Thanks. The error message has disappeared and the program is working now.
